version: "3.8"

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      DB_HOST: .
      MYSQL_DATABASE: "main"
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "test"
      MYSQL_TCP_PORT: 17011
    ports:
      - "17011:17011"
    volumes:
      - ./mySQLData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17011"]
      interval: 5s
      timeout: 10s
      retries: 10

  # balance-api:
  #   build:
  #     context: ./
  #     dockerfile: ./balance/Dockerfile
  #   restart: on-failure
  #   environment:
  #     PORT: 17012
  #     MYSQL_URI: "mysql+pymysql://root:test@database:17011/main"
  #     TESTING_URI: "mysql+pymysql://root:test@database:17011/test"
  #     TESTING: false
  #     SQLALCHEMY_WARN_20: 1
  #   volumes:
  #     - ./balance:/app
  #   ports:
  #     - "17012:17012"
  #   depends_on:
  #     database:
  #       condition: service_healthy

  users-api:
    build:
      context: ./
      dockerfile: ./users/Dockerfile
    restart: on-failure
    environment:
      PORT: 17010
      MYSQL_URI: "mysql+pymysql://root:test@database:17011/main"
      TESTING_URI: "mysql+pymysql://root:test@database:17011/test"
      TESTING: false
      SQLALCHEMY_WARN_20: 1
    volumes:
      - ./users:/app
    ports:
      - "17010:17010"
    depends_on:
      # balance-api:
      #   condition: service_started
      database:
        condition: service_healthy